---
#installing nginx and postgresql
- name: installing the web browsers
  hosts: localhost
  tasks:
  - name: Install nginx
    apt: name=nginx state=latest
    tags: nginx

  - name: restart nginx
    service:
      name: nginx
      state: started

  - name: Install PostgreSQL
    apt: name=postgresql state=latest
    tags: PostgreSQL

  - name: Start PostgreSQL
    service:
      name: postgresql
      state: started




