---
- name: Play1-install apache
  hosts: target2
  become: true
  become_method: sudo
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
      when: ansible_distribution == 'Ubuntu'
    - name: install apache2
      yum: name=httpd update_cache=yes state=latest
      when: ansible_distribution == 'CentOS'
    - name: displaying "hello world"
      debug: msg="hello world"
      tags:
        - tag1
- name: Play2-install nginx
  hosts: all
  become: true
  become_method: sudo
  tags:
    - tag2
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes state=latest
      when: ansible_distribution == 'Ubuntu'
    - name: install nginx
      yum: name=nginx update_cache=yes state=latest
      when: ansible_distribution == 'CentOS'
    - name: debug module displays message in control machine
      debug: msg="have a good day"
      tags:
        - mymessage
    - name: shell module displays message in host machine.
      shell: echo "yet another task"
      tags:
        - always
