---
- name: testing includes
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - include: apache.yml
    - include: content.yml
    - include: create_folder.yml
    - include: content.yml
- include: nginx.yml
