---
# tasks file for mysql
- name: install the mysql server with dependecies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items:
    - mysql-server
    - python3-pip
    - libmysqlclient-dev
    - python3-dev
    - python3-mysqldb
    - mysql-client
    - python3-setuptools
    - build-essential
    - python3

- name: Update MySQL Configuration file to accept connections from all interfaces
  ini_file:
      path: /etc/mysql/my.cnf
      section: mysqld
      option: bind-address
      value: 0.0.0.0
  tags:
    - acc

- name: start the mysql server
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Application Database
  mysql_db: name='employee_db' state=present

- name: Create Application DB User
  mysql_user: name='db_user' password='Passw0rd' priv='*.*:ALL' host='%' state='present'

- name: Re-start MySQL Service
  service:
      name: mysql
      state: restarted
      enabled: yes
  tags:
    - bcd
